# Generated by Django 2.0.1 on 2018-01-27 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_resume_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='pdf',
            field=models.FileField(upload_to='personalSite/static'),
        ),
    ]
